server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CLIENTS
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    sql:
      init:
        mode: always
        schema-locations: classpath:database/initDB.sql
        data-locations: classpath:database/populateDB.sql
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  feign:
    hystrix:
      enabled: false

app:
  discount: 10

clients:
  url: http://localhost:8081