feign:
  hystrix:
    enabled: false
clientApp:
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/Clients
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        mode: always
        schema-locations: classpath:database/initDB.sql
        data-locations: classpath:database/populateDB.sql
app:
  discount: 10
clients:
  url: http://localhost:8081